# Generated by Django 2.1.2 on 2018-12-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорія',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('manufacturer_name', models.CharField(max_length=200, verbose_name='Виробник')),
                ('indications_for_use', models.TextField(blank=True, verbose_name='Показання для застосування')),
                ('contraindications', models.TextField(blank=True, verbose_name='Протипоказання')),
                ('application_and_dose', models.TextField(blank=True, verbose_name='Спосіб застосування та дози')),
                ('term', models.CharField(max_length=200, verbose_name='Термін дії')),
                ('storage', models.TextField(blank=True, verbose_name='Умови зберігання')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Кількість на складі')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('img', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Зображення')),
                ('available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.Category', verbose_name='Категорія')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='medicine',
            index_together={('id', 'slug')},
        ),
    ]
