# Generated by Django 2.1.2 on 2018-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, upload_to='medicines/%Y/%m/%d/', verbose_name='Зображення'),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AlterIndexTogether(
            name='medicine',
            index_together={('id',)},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
